const firstString = 'qwertyuiop[]';
console.log(firstString.charAt(0));
console.log(firstString.charAt(12));
console.log(firstString.indexOf('['));
console.log(firstString.indexOf(']'));
console.log(firstString);
const secondString = 'asdfghjkl;';
console.log(secondString.charAt(0));
console.log(secondString.charAt(10));
console.log(secondString.indexOf('['));
console.log(secondString.indexOf(']'));
console.log(secondString);
const thirdString = 'zxcvbnm,./';
console.log(thirdString.charAt(0));
console.log(thirdString.charAt(10));
console.log(thirdString.indexOf('['));
console.log(thirdString.indexOf(']'));
console.log(thirdString);
const a = 12;
console.log(a);
const b = 10;
console.log(b);
const c = 10;
console.log(c);
const message = `${firstString} ${secondString} ${thirdString} ${a} ${b} ${c}`;
console.log (message);
